-- Project Membership Foundation.
--
-- Scope:
-- - Create public.project_members as the stable project membership authority.
-- - Link membership to public.projects(id) and public.employees(id).
-- - Preserve historical membership by revoking rows instead of hard deleting.
-- - Enable RLS with minimum Admin Workspace project policies.
--
-- This migration intentionally does not:
-- - Backfill live data.
-- - Add projects/phases/tasks/staff_tasks RLS policies.
-- - Modify projects, phases, tasks, staff_tasks, employees, attendance, finance,
--   or auth.users.

begin;

do $$
begin
  if to_regclass('public.projects') is null then
    raise exception 'Precondition failed: public.projects does not exist.';
  end if;

  if to_regclass('public.employees') is null then
    raise exception 'Precondition failed: public.employees does not exist.';
  end if;

  if to_regprocedure('public.current_employee_id()') is null then
    raise exception 'Precondition failed: public.current_employee_id() does not exist.';
  end if;

  if to_regprocedure('public.has_workspace_access(text)') is null then
    raise exception 'Precondition failed: public.has_workspace_access(text) does not exist.';
  end if;

  if to_regprocedure('public.has_permission(text)') is null then
    raise exception 'Precondition failed: public.has_permission(text) does not exist.';
  end if;

  if to_regclass('public.permissions') is null then
    raise exception 'Precondition failed: public.permissions does not exist.';
  end if;

  if not exists (select 1 from public.permissions where code = 'PROJECT_VIEW') then
    raise exception 'Precondition failed: PROJECT_VIEW permission does not exist.';
  end if;

  if not exists (select 1 from public.permissions where code = 'PROJECT_MANAGE') then
    raise exception 'Precondition failed: PROJECT_MANAGE permission does not exist.';
  end if;
end $$;

create table if not exists public.project_members (
  id bigint generated by default as identity primary key,
  project_id bigint not null,
  employee_id bigint not null,
  role_code text not null,
  status text not null default 'ACTIVE',
  granted_at timestamp with time zone not null default now(),
  granted_by_employee_id bigint null default public.current_employee_id(),
  revoked_at timestamp with time zone null,
  revoked_by_employee_id bigint null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint project_members_project_id_fkey
    foreign key (project_id)
    references public.projects(id)
    on update cascade
    on delete restrict,

  constraint project_members_employee_id_fkey
    foreign key (employee_id)
    references public.employees(id)
    on update cascade
    on delete restrict,

  constraint project_members_granted_by_employee_id_fkey
    foreign key (granted_by_employee_id)
    references public.employees(id)
    on update cascade
    on delete set null,

  constraint project_members_revoked_by_employee_id_fkey
    foreign key (revoked_by_employee_id)
    references public.employees(id)
    on update cascade
    on delete set null,

  constraint project_members_role_code_check
    check (role_code in (
      'PROJECT_OWNER',
      'PROJECT_MANAGER',
      'CREATIVE_LEAD',
      'CONTRIBUTOR'
    )),

  constraint project_members_status_check
    check (status in ('ACTIVE', 'REVOKED')),

  constraint project_members_revocation_state_check
    check (
      (status = 'ACTIVE' and revoked_at is null and revoked_by_employee_id is null)
      or (status = 'REVOKED' and revoked_at is not null)
    ),

  constraint project_members_grant_revoke_order_check
    check (
      revoked_at is null
      or granted_at <= revoked_at
    )
);

create unique index if not exists project_members_one_active_role
on public.project_members (project_id, employee_id, role_code)
where status = 'ACTIVE';

create index if not exists project_members_project_id_idx
on public.project_members (project_id);

create index if not exists project_members_employee_id_idx
on public.project_members (employee_id);

create index if not exists project_members_status_idx
on public.project_members (status);

create index if not exists project_members_project_status_idx
on public.project_members (project_id, status);

create or replace function public.set_project_members_audit_fields()
returns trigger
language plpgsql
set search_path = public, auth, pg_temp
as $$
declare
  actor_employee_id bigint;
begin
  actor_employee_id := public.current_employee_id();

  if tg_op = 'INSERT' then
    new.updated_at := now();

    if new.granted_at is null then
      new.granted_at := now();
    end if;

    if actor_employee_id is not null then
      new.granted_by_employee_id := actor_employee_id;
    end if;

    if new.status = 'ACTIVE' then
      new.revoked_at := null;
      new.revoked_by_employee_id := null;
    elsif new.status = 'REVOKED' and new.revoked_at is null then
      new.revoked_at := now();
      if actor_employee_id is not null then
        new.revoked_by_employee_id := actor_employee_id;
      end if;
    end if;

    return new;
  end if;

  new.created_at := old.created_at;
  new.granted_at := old.granted_at;
  new.granted_by_employee_id := old.granted_by_employee_id;
  new.updated_at := now();

  if new.project_id <> old.project_id
    or new.employee_id <> old.employee_id
    or new.role_code <> old.role_code then
    raise exception 'Project membership identity fields are immutable.';
  end if;

  if old.status = 'REVOKED' and new.status <> 'REVOKED' then
    raise exception 'Revoked project membership rows cannot be reactivated.';
  end if;

  if new.status = 'ACTIVE' then
    new.revoked_at := null;
    new.revoked_by_employee_id := null;
  elsif new.status = 'REVOKED' then
    if new.revoked_at is null then
      new.revoked_at := now();
    end if;

    if actor_employee_id is not null then
      new.revoked_by_employee_id := actor_employee_id;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists set_project_members_audit_fields on public.project_members;

create trigger set_project_members_audit_fields
before insert or update on public.project_members
for each row
execute function public.set_project_members_audit_fields();

alter table public.project_members enable row level security;

revoke all on public.project_members from public;
revoke all on public.project_members from anon;
revoke all on public.project_members from authenticated;
grant select, insert, update on public.project_members to authenticated;

revoke all on sequence public.project_members_id_seq from public;
revoke all on sequence public.project_members_id_seq from anon;
revoke all on sequence public.project_members_id_seq from authenticated;
grant usage on sequence public.project_members_id_seq to authenticated;

drop policy if exists "project members admin view select" on public.project_members;
create policy "project members admin view select"
on public.project_members
for select
to authenticated
using (
  public.has_workspace_access('ADMIN_WORKSPACE')
  and public.has_permission('PROJECT_VIEW')
);

drop policy if exists "project members admin manage insert" on public.project_members;
create policy "project members admin manage insert"
on public.project_members
for insert
to authenticated
with check (
  public.has_workspace_access('ADMIN_WORKSPACE')
  and public.has_permission('PROJECT_MANAGE')
);

drop policy if exists "project members admin manage update" on public.project_members;
create policy "project members admin manage update"
on public.project_members
for update
to authenticated
using (
  public.has_workspace_access('ADMIN_WORKSPACE')
  and public.has_permission('PROJECT_MANAGE')
)
with check (
  public.has_workspace_access('ADMIN_WORKSPACE')
  and public.has_permission('PROJECT_MANAGE')
);

alter function public.set_project_members_audit_fields() owner to postgres;

comment on table public.project_members is
  'Project membership authority for workflow RLS. Do not use names or email as authorization identifiers.';

comment on column public.project_members.project_id is
  'Stable project FK. on delete restrict preserves membership history and prevents accidental project deletion while memberships exist.';

comment on column public.project_members.employee_id is
  'Stable employee FK for the project member.';

comment on column public.project_members.role_code is
  'Business role scoped to one project. Valid values: PROJECT_OWNER, PROJECT_MANAGER, CREATIVE_LEAD, CONTRIBUTOR.';

comment on column public.project_members.status is
  'ACTIVE memberships participate in authorization. REVOKED memberships are historical and must retain revoked_at.';

comment on column public.project_members.granted_by_employee_id is
  'Grant actor derived from auth.uid() through public.current_employee_id() for authenticated writes. Bootstrap SQL may set a reviewed employee id.';

comment on column public.project_members.revoked_by_employee_id is
  'Revoke actor derived from auth.uid() through public.current_employee_id() for authenticated writes when available.';

comment on function public.set_project_members_audit_fields() is
  'Maintains project_members audit fields from auth.uid()-derived employee identity; does not trust client-provided actor fields.';

commit;
