-- Project Membership Foundation.
--
-- Scope:
-- - Create public.project_members as the stable project membership authority.
-- - Link membership to public.projects(id) and public.employees(id).
-- - Preserve historical membership by using status/left_at instead of hard delete.
-- - Enable RLS but do not open broad policies in this slice.
--
-- This migration intentionally does not:
-- - Backfill live data.
-- - Add projects/phases/tasks RLS policies.
-- - Create INSERT/UPDATE/DELETE policies.
-- - Modify projects, phases, tasks, staff_tasks, employees, attendance, or shifts.

create table if not exists public.project_members (
  id bigint generated by default as identity primary key,
  project_id bigint not null,
  employee_id bigint not null,
  member_role text not null default 'MEMBER',
  status text not null default 'ACTIVE',
  joined_at timestamp with time zone not null default now(),
  left_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint project_members_project_id_fkey
    foreign key (project_id)
    references public.projects(id)
    on update cascade
    on delete restrict,

  constraint project_members_employee_id_fkey
    foreign key (employee_id)
    references public.employees(id)
    on update cascade
    on delete restrict,

  constraint project_members_member_role_check
    check (member_role in (
      'PROJECT_OWNER',
      'PROJECT_MANAGER',
      'CREATIVE_LEAD',
      'MEMBER',
      'REVIEWER'
    )),

  constraint project_members_status_check
    check (status in ('ACTIVE', 'INACTIVE')),

  constraint project_members_left_at_check
    check (
      (status = 'ACTIVE' and left_at is null)
      or status = 'INACTIVE'
    ),

  constraint project_members_membership_dates_check
    check (
      left_at is null
      or joined_at <= left_at
    )
);

create unique index if not exists project_members_one_active_member
on public.project_members (project_id, employee_id)
where status = 'ACTIVE';

create index if not exists project_members_project_id_idx
on public.project_members (project_id);

create index if not exists project_members_employee_id_idx
on public.project_members (employee_id);

create index if not exists project_members_project_status_idx
on public.project_members (project_id, status);

create or replace function public.set_project_members_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_project_members_updated_at on public.project_members;

create trigger set_project_members_updated_at
before update on public.project_members
for each row
execute function public.set_project_members_updated_at();

alter table public.project_members enable row level security;

comment on table public.project_members is
  'Project membership authority for workflow RLS. Do not use names or email as authorization identifiers.';

comment on column public.project_members.project_id is
  'Stable project FK. on delete restrict preserves membership history and prevents accidental project deletion while memberships exist.';

comment on column public.project_members.employee_id is
  'Stable employee FK derived from auth.users.id -> employees.auth_user_id -> employees.id.';

comment on column public.project_members.member_role is
  'Business role scoped to one project. Valid values: PROJECT_OWNER, PROJECT_MANAGER, CREATIVE_LEAD, MEMBER, REVIEWER.';

comment on column public.project_members.status is
  'ACTIVE memberships participate in authorization. INACTIVE memberships are historical; left_at records when membership ended if known.';
