-- Purpose:
-- Move production workflow data out of system_settings and into dedicated
-- projects, phases, and tasks tables. system_settings remains for application
-- configuration such as automatic email reminder settings.
--
-- Impact:
-- Existing records in system_settings where group_name = 'PRODUCTION_WORKFLOW'
-- are copied into the workflow tables. Existing workflow tables are preserved
-- and only missing columns are added.
--
-- Rollback:
-- Keep system_settings records until the new UI has been verified. To roll
-- back app code, switch readers/writers back to system_settings. To remove
-- the new columns/tables after rollback, drop tasks, phases, projects only if
-- they are not used by other screens.

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.phases (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  phase_id bigint not null references public.phases(id) on delete cascade,
  name text not null,
  assignee text,
  deadline text,
  note text,
  status text not null default 'TODO',
  created_at timestamptz not null default now()
);

alter table public.projects add column if not exists name text;
alter table public.projects add column if not exists project_deadline text;
alter table public.projects add column if not exists drive_link text;
alter table public.phases add column if not exists status text not null default 'TODO';
alter table public.phases add column if not exists name text;
alter table public.phases add column if not exists order_index integer not null default 0;
alter table public.tasks add column if not exists deadline text;
alter table public.tasks add column if not exists note text;
alter table public.tasks add column if not exists status text not null default 'TODO';
alter table public.tasks add column if not exists name text;
alter table public.tasks add column if not exists assignee_id bigint;
alter table public.tasks add column if not exists assignee_name text;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'projects' and column_name = 'project_name'
  ) then
    execute 'update public.projects set name = coalesce(nullif(name, ''''), project_name) where coalesce(name, '''') = ''''';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'projects' and column_name = 'deadline'
  ) then
    execute 'update public.projects set project_deadline = coalesce(project_deadline, deadline)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'projects' and column_name = 'project_drive_link'
  ) then
    execute 'update public.projects set drive_link = coalesce(drive_link, project_drive_link)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'phases' and column_name = 'phase_name'
  ) then
    execute 'update public.phases set name = coalesce(nullif(name, ''''), phase_name) where coalesce(name, '''') = ''''';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'phases' and column_name = 'sort_order'
  ) then
    execute 'update public.phases set order_index = coalesce(order_index, sort_order)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'phases' and column_name = 'phase_status'
  ) then
    execute 'update public.phases set status = coalesce(nullif(status, ''''), phase_status) where coalesce(status, '''') = ''''';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'task_name'
  ) then
    execute 'update public.tasks set name = coalesce(nullif(name, ''''), task_name) where coalesce(name, '''') = ''''';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'employee_id'
  ) then
    execute 'update public.tasks set assignee_id = coalesce(assignee_id, employee_id)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'employee_name'
  ) then
    execute 'update public.tasks set assignee_name = coalesce(assignee_name, employee_name)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'description'
  ) then
    execute 'update public.tasks set note = coalesce(note, description)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'due_date'
  ) then
    execute 'update public.tasks set deadline = coalesce(deadline, due_date)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'task_status'
  ) then
    execute 'update public.tasks set status = coalesce(nullif(status, ''''), task_status) where coalesce(status, '''') = ''''';
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'phases_project_id_fkey'
      and conrelid = 'public.phases'::regclass
  ) then
    begin
      alter table public.phases
        add constraint phases_project_id_fkey
        foreign key (project_id)
        references public.projects(id)
        on delete cascade
        not valid;
    exception when others then
      raise notice 'Could not add phases_project_id_fkey: %', sqlerrm;
    end;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'tasks_phase_id_fkey'
      and conrelid = 'public.tasks'::regclass
  ) then
    begin
      alter table public.tasks
        add constraint tasks_phase_id_fkey
        foreign key (phase_id)
        references public.phases(id)
        on delete cascade
        not valid;
    exception when others then
      raise notice 'Could not add tasks_phase_id_fkey: %', sqlerrm;
    end;
  end if;
end $$;

create index if not exists phases_project_id_order_index_idx
  on public.phases(project_id, order_index);

create index if not exists tasks_phase_id_idx
  on public.tasks(phase_id);

with workflow_settings as (
  select
    ss.key,
    ss.value as phase_status,
    split_part(ss.config_name, ' - ', 1) as project_name,
    nullif(substring(ss.config_name from position(' - ' in ss.config_name) + 3), '') as phase_name,
    coalesce(ss.description::jsonb, '{}'::jsonb) as payload,
    row_number() over (
      partition by split_part(ss.config_name, ' - ', 1)
      order by ss.key
    ) - 1 as phase_order
  from public.system_settings ss
  where ss.group_name = 'PRODUCTION_WORKFLOW'
    and ss.config_name is not null
),
inserted_projects as (
  insert into public.projects (name, project_deadline, drive_link)
  select
    project_name,
    max(payload->>'project_deadline'),
    max(payload->>'project_drive_link')
  from workflow_settings
  where project_name <> ''
    and not exists (
      select 1
      from public.projects p
      where p.name = workflow_settings.project_name
    )
  group by project_name
  returning id, name
),
all_projects as (
  select id, name from public.projects
),
inserted_phases as (
  insert into public.phases (project_id, name, order_index, status)
  select
    p.id,
    coalesce(ws.phase_name, 'Giai doan ' || (ws.phase_order + 1)::text),
    ws.phase_order,
    coalesce(ws.phase_status, case when ws.phase_order = 0 then 'DOING' else 'TODO' end)
  from workflow_settings ws
  join all_projects p on p.name = ws.project_name
  where not exists (
    select 1
    from public.phases ph
    where ph.project_id = p.id
      and ph.order_index = ws.phase_order
      and ph.name = coalesce(ws.phase_name, 'Giai doan ' || (ws.phase_order + 1)::text)
  )
  returning id, project_id, name, order_index
),
phase_map as (
  select
    ws.payload,
    ph.id as phase_id
  from workflow_settings ws
  join all_projects p on p.name = ws.project_name
  join public.phases ph
    on ph.project_id = p.id
   and ph.order_index = ws.phase_order
   and ph.name = coalesce(ws.phase_name, 'Giai doan ' || (ws.phase_order + 1)::text)
)
insert into public.tasks (phase_id, name, assignee, deadline, note, status)
select
  pm.phase_id,
  task_item->>'name',
  task_item->>'assignee',
  task_item->>'deadline',
  task_item->>'note',
  coalesce(task_item->>'status', 'TODO')
from phase_map pm
cross join lateral jsonb_array_elements(coalesce(pm.payload->'tasks_list', '[]'::jsonb)) task_item
where coalesce(task_item->>'name', '') <> ''
  and not exists (
    select 1
    from public.tasks t
    where t.phase_id = pm.phase_id
      and t.name = task_item->>'name'
  );

grant select, insert, update, delete on public.projects to anon, authenticated;
grant select, insert, update, delete on public.phases to anon, authenticated;
grant select, insert, update, delete on public.tasks to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

alter table public.projects enable row level security;
alter table public.phases enable row level security;
alter table public.tasks enable row level security;

drop policy if exists "workflow projects public access" on public.projects;
create policy "workflow projects public access"
  on public.projects
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "workflow phases public access" on public.phases;
create policy "workflow phases public access"
  on public.phases
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "workflow tasks public access" on public.tasks;
create policy "workflow tasks public access"
  on public.tasks
  for all
  to anon, authenticated
  using (true)
  with check (true);

notify pgrst, 'reload schema';
