-- Access & Permission Foundation Slice 1.
--
-- Scope:
-- - Create workspace access and employee permission override tables.
-- - Seed the stable permission catalog.
-- - Create read-only authorization helpers.
-- - Enable RLS on new foundation tables.
-- - Add minimal read policies only.
--
-- This migration intentionally does not:
-- - Backfill any employee access or permissions.
-- - Replace public.is_app_admin().
-- - Modify existing RLS policies.
-- - Modify admin/staff routes, middleware, menus, employees.role, or project_members.
-- - Create Auth users or send invites.

begin;

create table if not exists public.employee_workspace_access (
  id bigint generated by default as identity primary key,
  employee_id bigint not null,
  workspace text not null,
  status text not null default 'ACTIVE',
  granted_at timestamp with time zone not null default now(),
  granted_by_employee_id bigint null,
  revoked_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint employee_workspace_access_employee_id_fkey
    foreign key (employee_id)
    references public.employees(id)
    on update cascade
    on delete restrict,

  constraint employee_workspace_access_granted_by_employee_id_fkey
    foreign key (granted_by_employee_id)
    references public.employees(id)
    on update cascade
    on delete set null,

  constraint employee_workspace_access_workspace_check
    check (workspace in ('STAFF_WORKSPACE', 'ADMIN_WORKSPACE')),

  constraint employee_workspace_access_status_check
    check (status in ('ACTIVE', 'INACTIVE')),

  constraint employee_workspace_access_revoked_check
    check (
      (status = 'ACTIVE' and revoked_at is null)
      or status = 'INACTIVE'
    )
);

create unique index if not exists employee_workspace_access_one_active
on public.employee_workspace_access (employee_id, workspace)
where status = 'ACTIVE';

create index if not exists employee_workspace_access_employee_id_idx
on public.employee_workspace_access (employee_id);

create index if not exists employee_workspace_access_workspace_status_idx
on public.employee_workspace_access (workspace, status);

create table if not exists public.permissions (
  code text primary key,
  description text null,
  created_at timestamp with time zone not null default now()
);

insert into public.permissions (code, description)
values
  ('EMPLOYEE_VIEW', 'View employee list and non-sensitive employee data'),
  ('EMPLOYEE_MANAGE', 'Create, update, and deactivate employees'),
  ('ACCOUNT_MANAGE', 'Manage account access, invites, reset links, and permissions'),
  ('FINANCE_VIEW', 'View finance records'),
  ('FINANCE_CREATE', 'Create finance records'),
  ('FINANCE_UPDATE', 'Update finance records'),
  ('FINANCE_DELETE', 'Delete finance records'),
  ('PROJECT_VIEW', 'View projects'),
  ('PROJECT_MANAGE', 'Manage projects'),
  ('PROJECT_ASSIGN', 'Assign project work'),
  ('PROJECT_REVIEW', 'Review project work'),
  ('ATTENDANCE_VIEW', 'View attendance'),
  ('ATTENDANCE_MANAGE', 'Manage attendance'),
  ('SYSTEM_SETTINGS_VIEW', 'View system settings'),
  ('SYSTEM_SETTINGS_MANAGE', 'Manage system settings'),
  ('EMAIL_TEMPLATE_VIEW', 'View email templates'),
  ('EMAIL_TEMPLATE_MANAGE', 'Manage email templates')
on conflict (code) do nothing;

create table if not exists public.employee_permissions (
  id bigint generated by default as identity primary key,
  employee_id bigint not null,
  permission_code text not null,
  effect text not null,
  status text not null default 'ACTIVE',
  granted_at timestamp with time zone not null default now(),
  granted_by_employee_id bigint null,
  revoked_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint employee_permissions_employee_id_fkey
    foreign key (employee_id)
    references public.employees(id)
    on update cascade
    on delete restrict,

  constraint employee_permissions_permission_code_fkey
    foreign key (permission_code)
    references public.permissions(code)
    on update cascade
    on delete restrict,

  constraint employee_permissions_granted_by_employee_id_fkey
    foreign key (granted_by_employee_id)
    references public.employees(id)
    on update cascade
    on delete set null,

  constraint employee_permissions_effect_check
    check (effect in ('ALLOW', 'DENY')),

  constraint employee_permissions_status_check
    check (status in ('ACTIVE', 'INACTIVE')),

  constraint employee_permissions_revoked_check
    check (
      (status = 'ACTIVE' and revoked_at is null)
      or status = 'INACTIVE'
    )
);

create unique index if not exists employee_permissions_one_active_effect
on public.employee_permissions (employee_id, permission_code, effect)
where status = 'ACTIVE';

create index if not exists employee_permissions_employee_id_idx
on public.employee_permissions (employee_id);

create index if not exists employee_permissions_permission_status_idx
on public.employee_permissions (permission_code, status);

create or replace function public.set_access_permissions_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_employee_workspace_access_updated_at on public.employee_workspace_access;
create trigger set_employee_workspace_access_updated_at
before update on public.employee_workspace_access
for each row
execute function public.set_access_permissions_updated_at();

drop trigger if exists set_employee_permissions_updated_at on public.employee_permissions;
create trigger set_employee_permissions_updated_at
before update on public.employee_permissions
for each row
execute function public.set_access_permissions_updated_at();

create or replace function public.current_employee_id()
returns bigint
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select e.id
  from public.employees e
  where e.auth_user_id = (select auth.uid())
    and e.status = 'ACTIVE'
    and coalesce(e.is_active, true) = true
  limit 1;
$$;

create or replace function public.has_workspace_access(workspace_code text)
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select
    workspace_code in ('STAFF_WORKSPACE', 'ADMIN_WORKSPACE')
    and public.current_employee_id() is not null
    and exists (
      select 1
      from public.employee_workspace_access access
      where access.employee_id = public.current_employee_id()
        and access.workspace = workspace_code
        and access.status = 'ACTIVE'
        and access.revoked_at is null
    );
$$;

create or replace function public.has_permission(permission_code text)
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select
    public.current_employee_id() is not null
    and exists (
      select 1
      from public.permissions p
      where p.code = permission_code
    )
    and not exists (
      select 1
      from public.employee_permissions ep
      where ep.employee_id = public.current_employee_id()
        and ep.permission_code = permission_code
        and ep.effect = 'DENY'
        and ep.status = 'ACTIVE'
        and ep.revoked_at is null
    )
    and exists (
      select 1
      from public.employee_permissions ep
      where ep.employee_id = public.current_employee_id()
        and ep.permission_code = permission_code
        and ep.effect = 'ALLOW'
        and ep.status = 'ACTIVE'
        and ep.revoked_at is null
    );
$$;

create or replace function public.can_access_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select public.has_workspace_access('ADMIN_WORKSPACE');
$$;

create or replace function public.can_access_staff()
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select public.has_workspace_access('STAFF_WORKSPACE');
$$;

alter function public.set_access_permissions_updated_at() owner to postgres;
alter function public.current_employee_id() owner to postgres;
alter function public.has_workspace_access(text) owner to postgres;
alter function public.has_permission(text) owner to postgres;
alter function public.can_access_admin() owner to postgres;
alter function public.can_access_staff() owner to postgres;

comment on function public.current_employee_id() is
  'Returns the active employees.id mapped from auth.uid() through employees.auth_user_id. Does not accept client-provided identity.';

comment on function public.has_workspace_access(text) is
  'Returns whether the current authenticated employee has active workspace access. Uses auth.uid() only.';

comment on function public.has_permission(text) is
  'Returns whether the current authenticated employee has an active ALLOW permission without an active DENY override. Uses auth.uid() only.';

comment on function public.can_access_admin() is
  'Returns whether the current authenticated employee can access the Admin Workspace.';

comment on function public.can_access_staff() is
  'Returns whether the current authenticated employee can access the Staff Workspace.';

revoke all on function public.current_employee_id() from public;
revoke all on function public.current_employee_id() from anon;
revoke all on function public.current_employee_id() from authenticated;
revoke all on function public.has_workspace_access(text) from public;
revoke all on function public.has_workspace_access(text) from anon;
revoke all on function public.has_workspace_access(text) from authenticated;
revoke all on function public.has_permission(text) from public;
revoke all on function public.has_permission(text) from anon;
revoke all on function public.has_permission(text) from authenticated;
revoke all on function public.can_access_admin() from public;
revoke all on function public.can_access_admin() from anon;
revoke all on function public.can_access_admin() from authenticated;
revoke all on function public.can_access_staff() from public;
revoke all on function public.can_access_staff() from anon;
revoke all on function public.can_access_staff() from authenticated;

grant execute on function public.current_employee_id() to authenticated;
grant execute on function public.has_workspace_access(text) to authenticated;
grant execute on function public.has_permission(text) to authenticated;
grant execute on function public.can_access_admin() to authenticated;
grant execute on function public.can_access_staff() to authenticated;

revoke all on public.employee_workspace_access from public;
revoke all on public.employee_workspace_access from anon;
revoke all on public.employee_workspace_access from authenticated;
revoke all on public.permissions from public;
revoke all on public.permissions from anon;
revoke all on public.permissions from authenticated;
revoke all on public.employee_permissions from public;
revoke all on public.employee_permissions from anon;
revoke all on public.employee_permissions from authenticated;

grant select on public.employee_workspace_access to authenticated;
grant select on public.permissions to authenticated;
grant select on public.employee_permissions to authenticated;

alter table public.employee_workspace_access enable row level security;
alter table public.permissions enable row level security;
alter table public.employee_permissions enable row level security;

drop policy if exists "permissions authenticated select" on public.permissions;
create policy "permissions authenticated select"
on public.permissions
for select
to authenticated
using (true);

drop policy if exists "employee workspace access own select" on public.employee_workspace_access;
create policy "employee workspace access own select"
on public.employee_workspace_access
for select
to authenticated
using (employee_id = public.current_employee_id());

drop policy if exists "employee permissions own select" on public.employee_permissions;
create policy "employee permissions own select"
on public.employee_permissions
for select
to authenticated
using (employee_id = public.current_employee_id());

comment on table public.employee_workspace_access is
  'Workspace access history for Luminal ERP accounts. Authority is auth.users.id -> employees.auth_user_id -> employees.id.';

comment on table public.permissions is
  'Stable application permission catalog. Permission decisions must not come from frontend-submitted roles.';

comment on table public.employee_permissions is
  'Per-employee permission overrides. Stores ALLOW and DENY history without hard deleting revoked records.';

commit;
